### ISSUE TITLE
path error for demetra/msts/CompositeModel

### ISSUE THREAD

**Issue by pmbyron** [nbbrd/rjdssf#3]
When I source or run all seven R scripts in this repository, then try to run the jd3_ssf_model function, I get the following error:

Error in .jnew("demetra/msts/CompositeModel") : 
  java.lang.ClassNotFoundException

This seems to indicate that there is something wrong with the demetra/msts/CompositeModel path. Or am I doing something wrong?

**Comment by pmbyron** [comment]
I've found the error. in jd3_init.R, the .jaddClassPath() calls are pointing to the wrong file names and also are missing a level in the folder structure (assuming the working directory is the rjdssf-master folder). They instead should be:

```
.jaddClassPath("./inst/java/demetra-design-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./inst/java/demetra-sts-api-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./inst/java/demetra-sts-core-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./inst/java/demetra-sts-r-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./inst/java/demetra-toolkit-api-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./inst/java/demetra-toolkit-basic-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./inst/java/demetra-toolkit-modelling-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./inst/java/demetra-toolkit-r-1.0.0-SNAPSHOT.jar")
.jaddClassPath("./inst/java/demetra-toolkit-ssf-1.0.0-SNAPSHOT.jar")

```
It took a while to find the error, as the .jaddClassPath function didn't return an error when the .jar file didn't exist. (A discussion of why this is is here: https://github.com/s-u/rJava/issues/196) Therefore it may be prudent to instead use the following code:

```
loadjar <- function(path){
  if(!file.exists(path)) stop('.jar file does not exist')
  .jaddClassPath(path) 
}

loadjar("./inst/java/demetra-design-1.0.0-SNAPSHOT.jar")
loadjar("./inst/java/demetra-sts-api-1.0.0-SNAPSHOT.jar")
loadjar("./inst/java/demetra-sts-core-1.0.0-SNAPSHOT.jar")
loadjar("./inst/java/demetra-sts-r-1.0.0-SNAPSHOT.jar")
loadjar("./inst/java/demetra-toolkit-api-1.0.0-SNAPSHOT.jar")
loadjar("./inst/java/demetra-toolkit-basic-1.0.0-SNAPSHOT.jar")
loadjar("./inst/java/demetra-toolkit-modelling-1.0.0-SNAPSHOT.jar")
loadjar("./inst/java/demetra-toolkit-r-1.0.0-SNAPSHOT.jar")
loadjar("./inst/java/demetra-toolkit-ssf-1.0.0-SNAPSHOT.jar")

```

**Comment by palatej** [comment]
Thanks Peter. I will modify the code
